import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Provider from "./Provider";
import { Link as LinkMui, Typography } from "@mui/material";
import Link from "next/link";

const lato = Lato({
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Tamíz.LA",
    description: "Generated by Laboratorio-app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="es">
            <body className={lato.className} style={{ margin: 0 }}>
                <Provider>
                   
                    {children}
                </Provider>
            </body>
        </html>
    );
}
